// first install mongoose  /* npm install mongoose */
const mongoose = require('mongoose');
// even this localtion is not exist, mongo will create one
mongoose.connect('mongodb://localhost/fetcher', {useMongoClient: true});

// test if connect correctly

var db = mongoose.connection;
console.log('test1');
db.on('error,', console.error.bind(console, 'connection error:'));
console.log('test2')

var data = [ { id: 80044890,
    name: 'fullstack-course4',
    full_name: 'inh556/fullstack-course4',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/fullstack-course4',
    description: 'Example code for HTML, CSS, and Javascript for Web Developers Coursera Course',
    fork: true,
    url: 'https://api.github.com/repos/inh556/fullstack-course4',
    forks_url: 'https://api.github.com/repos/inh556/fullstack-course4/forks',
    keys_url: 'https://api.github.com/repos/inh556/fullstack-course4/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/fullstack-course4/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/fullstack-course4/teams',
    hooks_url: 'https://api.github.com/repos/inh556/fullstack-course4/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/fullstack-course4/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/fullstack-course4/events',
    assignees_url: 'https://api.github.com/repos/inh556/fullstack-course4/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/fullstack-course4/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/fullstack-course4/tags',
    blobs_url: 'https://api.github.com/repos/inh556/fullstack-course4/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/fullstack-course4/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/fullstack-course4/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/fullstack-course4/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/fullstack-course4/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/fullstack-course4/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/fullstack-course4/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/fullstack-course4/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/fullstack-course4/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/fullstack-course4/subscription',
    commits_url: 'https://api.github.com/repos/inh556/fullstack-course4/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/fullstack-course4/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/fullstack-course4/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/fullstack-course4/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/fullstack-course4/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/fullstack-course4/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/fullstack-course4/merges',
    archive_url: 'https://api.github.com/repos/inh556/fullstack-course4/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/fullstack-course4/downloads',
    issues_url: 'https://api.github.com/repos/inh556/fullstack-course4/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/fullstack-course4/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/fullstack-course4/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/fullstack-course4/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/fullstack-course4/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/fullstack-course4/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/fullstack-course4/deployments',
    created_at: '2017-01-25T18:39:40Z',
    updated_at: '2017-01-25T18:39:44Z',
    pushed_at: '2017-01-20T00:47:23Z',
    git_url: 'git://github.com/inh556/fullstack-course4.git',
    ssh_url: 'git@github.com:inh556/fullstack-course4.git',
    clone_url: 'https://github.com/inh556/fullstack-course4.git',
    svn_url: 'https://github.com/inh556/fullstack-course4',
    homepage: null,
    size: 31573,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } },
  { id: 120816202,
    name: 'giraffeMaker',
    full_name: 'inh556/giraffeMaker',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/giraffeMaker',
    description: 'Methods of object instantiation and inheritence in Javascript',
    fork: true,
    url: 'https://api.github.com/repos/inh556/giraffeMaker',
    forks_url: 'https://api.github.com/repos/inh556/giraffeMaker/forks',
    keys_url: 'https://api.github.com/repos/inh556/giraffeMaker/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/giraffeMaker/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/giraffeMaker/teams',
    hooks_url: 'https://api.github.com/repos/inh556/giraffeMaker/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/giraffeMaker/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/giraffeMaker/events',
    assignees_url: 'https://api.github.com/repos/inh556/giraffeMaker/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/giraffeMaker/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/giraffeMaker/tags',
    blobs_url: 'https://api.github.com/repos/inh556/giraffeMaker/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/giraffeMaker/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/giraffeMaker/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/giraffeMaker/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/giraffeMaker/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/giraffeMaker/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/giraffeMaker/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/giraffeMaker/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/giraffeMaker/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/giraffeMaker/subscription',
    commits_url: 'https://api.github.com/repos/inh556/giraffeMaker/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/giraffeMaker/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/giraffeMaker/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/giraffeMaker/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/giraffeMaker/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/giraffeMaker/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/giraffeMaker/merges',
    archive_url: 'https://api.github.com/repos/inh556/giraffeMaker/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/giraffeMaker/downloads',
    issues_url: 'https://api.github.com/repos/inh556/giraffeMaker/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/giraffeMaker/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/giraffeMaker/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/giraffeMaker/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/giraffeMaker/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/giraffeMaker/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/giraffeMaker/deployments',
    created_at: '2018-02-08T20:48:38Z',
    updated_at: '2018-02-08T20:48:40Z',
    pushed_at: '2018-01-11T23:18:31Z',
    git_url: 'git://github.com/inh556/giraffeMaker.git',
    ssh_url: 'git@github.com:inh556/giraffeMaker.git',
    clone_url: 'https://github.com/inh556/giraffeMaker.git',
    svn_url: 'https://github.com/inh556/giraffeMaker',
    homepage: '',
    size: 59,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } },
  { id: 119109572,
    name: 'JS-',
    full_name: 'inh556/JS-',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/JS-',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/inh556/JS-',
    forks_url: 'https://api.github.com/repos/inh556/JS-/forks',
    keys_url: 'https://api.github.com/repos/inh556/JS-/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/JS-/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/JS-/teams',
    hooks_url: 'https://api.github.com/repos/inh556/JS-/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/JS-/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/JS-/events',
    assignees_url: 'https://api.github.com/repos/inh556/JS-/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/JS-/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/JS-/tags',
    blobs_url: 'https://api.github.com/repos/inh556/JS-/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/JS-/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/JS-/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/JS-/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/JS-/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/JS-/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/JS-/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/JS-/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/JS-/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/JS-/subscription',
    commits_url: 'https://api.github.com/repos/inh556/JS-/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/JS-/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/JS-/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/JS-/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/JS-/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/JS-/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/JS-/merges',
    archive_url: 'https://api.github.com/repos/inh556/JS-/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/JS-/downloads',
    issues_url: 'https://api.github.com/repos/inh556/JS-/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/JS-/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/JS-/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/JS-/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/JS-/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/JS-/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/JS-/deployments',
    created_at: '2018-01-26T22:20:09Z',
    updated_at: '2018-01-26T22:31:37Z',
    pushed_at: '2018-01-29T04:32:17Z',
    git_url: 'git://github.com/inh556/JS-.git',
    ssh_url: 'git@github.com:inh556/JS-.git',
    clone_url: 'https://github.com/inh556/JS-.git',
    svn_url: 'https://github.com/inh556/JS-',
    homepage: null,
    size: 85,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } },
  { id: 127660884,
    name: 'js--interview-questions',
    full_name: 'inh556/js--interview-questions',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/js--interview-questions',
    description: ':grey_question::question::grey_question: Notes from technical (javascript) interviews. Tasks and quiz for different topics to discuss on interview / check self skills in javascript',
    fork: true,
    url: 'https://api.github.com/repos/inh556/js--interview-questions',
    forks_url: 'https://api.github.com/repos/inh556/js--interview-questions/forks',
    keys_url: 'https://api.github.com/repos/inh556/js--interview-questions/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/js--interview-questions/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/js--interview-questions/teams',
    hooks_url: 'https://api.github.com/repos/inh556/js--interview-questions/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/js--interview-questions/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/js--interview-questions/events',
    assignees_url: 'https://api.github.com/repos/inh556/js--interview-questions/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/js--interview-questions/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/js--interview-questions/tags',
    blobs_url: 'https://api.github.com/repos/inh556/js--interview-questions/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/js--interview-questions/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/js--interview-questions/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/js--interview-questions/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/js--interview-questions/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/js--interview-questions/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/js--interview-questions/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/js--interview-questions/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/js--interview-questions/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/js--interview-questions/subscription',
    commits_url: 'https://api.github.com/repos/inh556/js--interview-questions/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/js--interview-questions/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/js--interview-questions/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/js--interview-questions/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/js--interview-questions/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/js--interview-questions/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/js--interview-questions/merges',
    archive_url: 'https://api.github.com/repos/inh556/js--interview-questions/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/js--interview-questions/downloads',
    issues_url: 'https://api.github.com/repos/inh556/js--interview-questions/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/js--interview-questions/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/js--interview-questions/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/js--interview-questions/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/js--interview-questions/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/js--interview-questions/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/js--interview-questions/deployments',
    created_at: '2018-04-01T18:41:17Z',
    updated_at: '2018-04-01T18:41:19Z',
    pushed_at: '2018-03-31T08:38:10Z',
    git_url: 'git://github.com/inh556/js--interview-questions.git',
    ssh_url: 'git@github.com:inh556/js--interview-questions.git',
    clone_url: 'https://github.com/inh556/js--interview-questions.git',
    svn_url: 'https://github.com/inh556/js--interview-questions',
    homepage: '',
    size: 122,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } },
  { id: 91109780,
    name: 'Python',
    full_name: 'inh556/Python',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/Python',
    description: 'basic concept of python',
    fork: false,
    url: 'https://api.github.com/repos/inh556/Python',
    forks_url: 'https://api.github.com/repos/inh556/Python/forks',
    keys_url: 'https://api.github.com/repos/inh556/Python/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/Python/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/Python/teams',
    hooks_url: 'https://api.github.com/repos/inh556/Python/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/Python/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/Python/events',
    assignees_url: 'https://api.github.com/repos/inh556/Python/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/Python/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/Python/tags',
    blobs_url: 'https://api.github.com/repos/inh556/Python/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/Python/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/Python/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/Python/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/Python/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/Python/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/Python/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/Python/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/Python/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/Python/subscription',
    commits_url: 'https://api.github.com/repos/inh556/Python/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/Python/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/Python/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/Python/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/Python/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/Python/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/Python/merges',
    archive_url: 'https://api.github.com/repos/inh556/Python/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/Python/downloads',
    issues_url: 'https://api.github.com/repos/inh556/Python/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/Python/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/Python/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/Python/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/Python/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/Python/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/Python/deployments',
    created_at: '2017-05-12T16:23:36Z',
    updated_at: '2017-06-07T16:16:27Z',
    pushed_at: '2017-08-31T04:03:48Z',
    git_url: 'git://github.com/inh556/Python.git',
    ssh_url: 'git@github.com:inh556/Python.git',
    clone_url: 'https://github.com/inh556/Python.git',
    svn_url: 'https://github.com/inh556/Python',
    homepage: null,
    size: 86,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'Python',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } },
  { id: 122809039,
    name: 'recursion-practice',
    full_name: 'inh556/recursion-practice',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/recursion-practice',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/inh556/recursion-practice',
    forks_url: 'https://api.github.com/repos/inh556/recursion-practice/forks',
    keys_url: 'https://api.github.com/repos/inh556/recursion-practice/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/recursion-practice/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/recursion-practice/teams',
    hooks_url: 'https://api.github.com/repos/inh556/recursion-practice/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/recursion-practice/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/recursion-practice/events',
    assignees_url: 'https://api.github.com/repos/inh556/recursion-practice/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/recursion-practice/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/recursion-practice/tags',
    blobs_url: 'https://api.github.com/repos/inh556/recursion-practice/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/recursion-practice/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/recursion-practice/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/recursion-practice/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/recursion-practice/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/recursion-practice/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/recursion-practice/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/recursion-practice/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/recursion-practice/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/recursion-practice/subscription',
    commits_url: 'https://api.github.com/repos/inh556/recursion-practice/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/recursion-practice/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/recursion-practice/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/recursion-practice/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/recursion-practice/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/recursion-practice/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/recursion-practice/merges',
    archive_url: 'https://api.github.com/repos/inh556/recursion-practice/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/recursion-practice/downloads',
    issues_url: 'https://api.github.com/repos/inh556/recursion-practice/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/recursion-practice/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/recursion-practice/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/recursion-practice/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/recursion-practice/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/recursion-practice/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/recursion-practice/deployments',
    created_at: '2018-02-25T05:47:44Z',
    updated_at: '2018-02-25T05:56:09Z',
    pushed_at: '2018-03-06T05:02:18Z',
    git_url: 'git://github.com/inh556/recursion-practice.git',
    ssh_url: 'git@github.com:inh556/recursion-practice.git',
    clone_url: 'https://github.com/inh556/recursion-practice.git',
    svn_url: 'https://github.com/inh556/recursion-practice',
    homepage: null,
    size: 333,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } },
  { id: 125446091,
    name: 'Toy-problems',
    full_name: 'inh556/Toy-problems',
    owner: 
     { login: 'inh556',
       id: 22806630,
       avatar_url: 'https://avatars1.githubusercontent.com/u/22806630?v=4',
       gravatar_id: '',
       url: 'https://api.github.com/users/inh556',
       html_url: 'https://github.com/inh556',
       followers_url: 'https://api.github.com/users/inh556/followers',
       following_url: 'https://api.github.com/users/inh556/following{/other_user}',
       gists_url: 'https://api.github.com/users/inh556/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/inh556/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/inh556/subscriptions',
       organizations_url: 'https://api.github.com/users/inh556/orgs',
       repos_url: 'https://api.github.com/users/inh556/repos',
       events_url: 'https://api.github.com/users/inh556/events{/privacy}',
       received_events_url: 'https://api.github.com/users/inh556/received_events',
       type: 'User',
       site_admin: false },
    private: false,
    html_url: 'https://github.com/inh556/Toy-problems',
    description: 'Toy problems practice',
    fork: false,
    url: 'https://api.github.com/repos/inh556/Toy-problems',
    forks_url: 'https://api.github.com/repos/inh556/Toy-problems/forks',
    keys_url: 'https://api.github.com/repos/inh556/Toy-problems/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/inh556/Toy-problems/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/inh556/Toy-problems/teams',
    hooks_url: 'https://api.github.com/repos/inh556/Toy-problems/hooks',
    issue_events_url: 'https://api.github.com/repos/inh556/Toy-problems/issues/events{/number}',
    events_url: 'https://api.github.com/repos/inh556/Toy-problems/events',
    assignees_url: 'https://api.github.com/repos/inh556/Toy-problems/assignees{/user}',
    branches_url: 'https://api.github.com/repos/inh556/Toy-problems/branches{/branch}',
    tags_url: 'https://api.github.com/repos/inh556/Toy-problems/tags',
    blobs_url: 'https://api.github.com/repos/inh556/Toy-problems/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/inh556/Toy-problems/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/inh556/Toy-problems/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/inh556/Toy-problems/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/inh556/Toy-problems/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/inh556/Toy-problems/languages',
    stargazers_url: 'https://api.github.com/repos/inh556/Toy-problems/stargazers',
    contributors_url: 'https://api.github.com/repos/inh556/Toy-problems/contributors',
    subscribers_url: 'https://api.github.com/repos/inh556/Toy-problems/subscribers',
    subscription_url: 'https://api.github.com/repos/inh556/Toy-problems/subscription',
    commits_url: 'https://api.github.com/repos/inh556/Toy-problems/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/inh556/Toy-problems/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/inh556/Toy-problems/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/inh556/Toy-problems/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/inh556/Toy-problems/contents/{+path}',
    compare_url: 'https://api.github.com/repos/inh556/Toy-problems/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/inh556/Toy-problems/merges',
    archive_url: 'https://api.github.com/repos/inh556/Toy-problems/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/inh556/Toy-problems/downloads',
    issues_url: 'https://api.github.com/repos/inh556/Toy-problems/issues{/number}',
    pulls_url: 'https://api.github.com/repos/inh556/Toy-problems/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/inh556/Toy-problems/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/inh556/Toy-problems/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/inh556/Toy-problems/labels{/name}',
    releases_url: 'https://api.github.com/repos/inh556/Toy-problems/releases{/id}',
    deployments_url: 'https://api.github.com/repos/inh556/Toy-problems/deployments',
    created_at: '2018-03-16T01:18:09Z',
    updated_at: '2018-03-17T20:13:31Z',
    pushed_at: '2018-03-17T20:13:29Z',
    git_url: 'git://github.com/inh556/Toy-problems.git',
    ssh_url: 'git@github.com:inh556/Toy-problems.git',
    clone_url: 'https://github.com/inh556/Toy-problems.git',
    svn_url: 'https://github.com/inh556/Toy-problems',
    homepage: null,
    size: 3,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true } } ]





	let repoSchema = mongoose.Schema({
	  name: String,
	  description: String,
	  folks: Number  
	});
	let Repo = mongoose.model('Repo', repoSchema);
	//let save = (data) => {
		console.log('connected to database');
		for(var i = 0; i < data.length; i++) {
			console.log('connected to database');
	  	var repo = new Repo ({"name": data[i].name, "description": data[i].description, "folks": data[i].folks});
			db.collection('repos').insert(repo);
	//}	
}




//module.exports.save = save;